@startregex
/auth/login (<<put>>)|/messages (<<get>>|<<post>>)|/users/\{user_id\} <<get>>|/teachers/\{teacher_id\} <<get>>|/scores <<get>>|/prize_cost|prizes(<<get>>|<<post>>)|/courses (/\{course_id\}|<<get>>)|/polls <<post>>|/teacher_estimates(<<get>>|<<post>>)
@endregex